# https://docs.codecov.com/docs/codecov-yaml
coverage:
  status:
    project:
      default:
        target: 93.14%
        informational: false
    patch:
      default:
        target: 80%
        informational: false