# https://docs.codecov.com/docs/codecov-yaml
coverage:
  status:
    project:
      default:
        target: 77.28%
        informational: false
    patch:
      default:
        target: 80%
        informational: false